# Generated by Django 6.0.2 on 2026-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('torte', 'Torte'), ('kolaci', 'Kolači'), ('keksi', 'Keksi'), ('dizana_lisnata_tijesta', 'Dizana i lisnata tijesta'), ('zamrznuti_deserti', 'Zamrznuti deserti'), ('ostalo', 'Ostalo')], default='ostalo', max_length=40),
        ),
    ]
